CREATE TABLE sales_data (
  ORDERNUMBER INT,
  QUANTITYORDERED INT,
  PRICEEACH NUMERIC(10,2),
  ORDERLINENUMBER INT,
  SALES NUMERIC(12,2),
  ORDERDATE DATE,
  STATUS VARCHAR(50),
  QTR_ID INT,
  MONTH_ID INT,
  YEAR_ID  INT,
  PRODUCTLINE VARCHAR(100),
  MSRP NUMERIC(10,2),
  PRODUCTCODE  VARCHAR(50),
  CUSTOMERNAME VARCHAR(255),
  PHONE VARCHAR(50),
  ADDRESSLINE1 VARCHAR(255),
  ADDRESSLINE2  VARCHAR(255),
  CITY  VARCHAR(100),
  STATE VARCHAR(100),
  POSTALCODE VARCHAR(20),
  COUNTRY VARCHAR(100),
  TERRITORY VARCHAR(50),
  CONTACTLASTNAME VARCHAR(100),
  CONTACTFIRSTNAME VARCHAR(100),
  DEALSIZE VARCHAR(20),
  PRIMARY KEY (ORDERNUMBER, ORDERLINENUMBER)
);


SELECT COUNT(*) FROM sales_data;
SELECT * FROM sales_data LIMIT 10;
